---
  resources:
    - name: spring-petclinic
      type: git
      source:
        uri: ((spring-petclinic-repo-uri))
        branch: master
    - name: build-scripts
      type: git
      source:
        uri: ((build-scripts-repo-uri))
        branch: master
    - name: deploy-app
      type: cf
      source:
        api: https://api.sys.watsonville.cf-app.com
        username: ((om-username))
        password: ((om-password))
        organization: system
        space: demo
        skip_cert_check: true
  jobs:
  - name: petclinic-deploy
    public: true
    serial: true
    plan:
    - get: spring-petclinic
      trigger: true
    - get: build-scripts
    - task: container-build
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: 
            repository: openjdk
            tag: latest
        inputs:
          - name: spring-petclinic
          - name: build-scripts
        run:
          path: build-scripts/build-scripts/spring-petclinic-build.sh  
    - put: deploy-app
      params: 
        manifest: spring-petclinic/manifest.yml