---
  resource_types:
    - name: slack-notification
      type: docker-image
      source:
        repository: cfcommunity/slack-notification-resource
  resources:
    - name: spring-music
      type: git
      source:
        uri: ((spring-music-repo-uri))
        branch: master
    - name: build-scripts
      type: git
      source:
        uri: ((build-scripts-repo-uri))
        branch: master
    - name: deploy-app
      type: cf
      source:
        api: https://api.sys.watsonville.cf-app.com
        username: admin
        password: YBcU1hFBEwcuR_msuxoZobO5hm6WjB30
        organization: system
        space: ksm-test
        skip_cert_check: true
  jobs:
    - name: gradle-build
      public: true
      serial: true
      plan:
        - get: spring-music
          trigger: true
        - get: build-scripts
        - task: gradle-build
          config:
            platform: linux
            image_resource:
              type: docker-image
              source: 
                repository: gradle
                tag: 6.5-jdk8
            inputs:
              - name: spring-music
              - name: build-scripts
            run:
              path: build-scripts/build-scripts/spring-music-build.sh  
        - put: deploy-app
          params: 
            manifest: spring-music/manifest.yml
        